name: debianize lxd

on: [push]

jobs:
  debianize-lxd:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          echo GO_VERSION=1.19.4 >> $GITHUB_ENV
          echo LXD_VERSION=5.14 >> $GITHUB_ENV
          echo PATH="/usr/local/go/bin:$PATH" >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install --yes devscripts debhelper

          curl -OL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz &&
            rm go${GO_VERSION}.linux-amd64.tar.gz

          curl --fail -SOL https://github.com/lxc/lxd/releases/download/lxd-${LXD_VERSION}/lxd-${LXD_VERSION}.tar.gz
          tar xf lxd-${LXD_VERSION}.tar.gz &&
            rm lxd-${LXD_VERSION}.tar.gz
          cd lxd-${LXD_VERSION} && \
            patch -p1  < ../disable-qemu-set-action.patch

      - name: debianize lxd
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OS: ${{ matrix.os }}
        run: |
          source /etc/lsb-release

          sed -i "s/__VERSION__/${LXD_VERSION}/g" debian/changelog
          sed -i "s/__VERSION__/${LXD_VERSION}/g" debian/rules
          sed -i "s/__DIST__/${DISTRIB_CODENAME}/g" debian/changelog

          cd lxd-${LXD_VERSION} &&
            go mod vendor &&
            cd -

          git clone --depth=1 "https://github.com/canonical/raft" lxd-${LXD_VERSION}/vendor/raft
          git clone --depth=1 "https://github.com/canonical/dqlite" lxd-${LXD_VERSION}/vendor/dqlite/

          SOURCE_VERSION=$(dpkg-parsechangelog --show-field Version | cut -d: -f2)
          echo SOURCE_VERSION=${SOURCE_VERSION} >> $GITHUB_ENV

          echo -n "$SIGNING_KEY" | base64 --decode | gpg --import
          echo "9C52118F1F982CED231CE6CE46C468585E4A8B6D:6:" > ownertrust
          gpg --import-ownertrust ownertrust

          debuild -d --no-tgz-check -k9C52118F1F982CED231CE6CE46C468585E4A8B6D -S

          cp ../lxd_${SOURCE_VERSION}.tar.xz ../lxd_${SOURCE_VERSION}.orig.tar.xz
          cp ../lxd_${SOURCE_VERSION}.tar.xz .

      - name: test debuild
        run: |
          mkdir _test_debuild
          cp lxd_${SOURCE_VERSION}.tar.xz _test_debuild
          tar xf lxd_${SOURCE_VERSION}.tar.xz -C _test_debuild
          cd _test_debuild/lxd-deb/ &&
            sudo apt build-dep . &&
            debuild -us -uc -b

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lxd build
          path: |
            lxd_*.tar.xz
            _test_debuild/*.deb

      - name: publish package to ppa
        if: github.ref == 'refs/heads/master'
        run: |
          echo "[thekev-ppa]" >> ~/.dput.cf
          echo "fqdn = ppa.launchpad.net" >> ~/.dput.cf
          echo "method = ftp" >> ~/.dput.cf
          echo "incoming = ~thekev./ubuntu/ppa/" >> ~/.dput.cf
          echo "login = anonymous" >> ~/.dput.cf
          echo "allow_unsigned_uploads = 0" >> ~/.dput.cf

          dput ppa:thekev./ppa ../lxd_*.changes
